[package]
authors = [ "Diggory Hardy <git@dhardy.name>" ]
name = "sn_routing_sims"
version = "0.1.2"

[dependencies]
clap = "2.18.0"
env_logger = "~0.3.5"
log = "~0.3.6"
rand = "~0.3.14"
rayon = "~0.5"
rustc-serialize = "~0.3.19"
